# Generated by Django 3.0.4 on 2020-05-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_connections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.TextField(default='[]', max_length=5000),
        ),
    ]
